language: csharp
solution: dips_lab1.sln
mono: none
dotnet: 2.0.0
dist: trusty
before_script:
- chmod a+x ./build.sh
- chmod a+x ./tests.sh
jobs:
  include:
  - stage: build
    script: "./build.sh"
  - stage: test
    script: "./tests.sh"
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: eoQEU++1Jblyc1Lm0HbELrP6NfXPOz4guGKzGtLMjXyZmdVELKpdKILsj0+DYrUwjiAydKMdXEuGFSYHHH+mseJsiKiPaT8Ed0IyrMjtoPPDBhdVZunnF5zKvkblUVyQwFb9GG/0IldMDUSkCFEMQ44RHprWR8HJhb2OvhlTdYuKx9yrQJKWp5uP0PBRMhcvHHXK7eWyXOSl8hFO4Er2Rnu7Pl5+tw9lmjmsjRAtg8gKm310VUnf2o5+fYw+93Ync+EHTw9oAi3c/8+oYU1XRoz+AFVVmABS6C26y/taUNNj20/Z1nI8OgvqNAzwDhkXzs1RsaEYhf2g+umCVMNwk7+2kD9jVFuD9KHFIrT1g3bST03eTa6lVz1JMTXxiyS/7MF7vVNk362iLbfshFgPuNh93adhqqVsZ1fthLUFCdwPwp7a5B7aOTTv6Iki3rY8sVeU+Mvjzp5/p8AAeY5sqNNm0jJQTN+qq4YhBkvZC0+Kz4zxIiaJoUxv4nyMZuQ/KaE6I88QAEPIhHWEzwoGZB5ef2pTCShI8uOh5c6c8RiFjg6iQfvXll0O4uNLQ0nwRFCQrZW4/ppVbyxYZ9YcYL+MxnT3XQfTKueGPxr1EceYpQrC5VKUqGCWThgpI5ZaFp0cO0ue2Zq+K84ehbMkfKrMiMC0D8nPmB5XzM/qNCQ=
      app: dipslab1
      on:
        repo: elavrenova/DipsLab1