language: csharp
solution: dips_lab1.sln
mono: none
dotnet: 2.0.0
dist: trusty
before_script:
- chmod a+x ./build.sh
- chmod a+x ./tests.sh
jobs:
  include:
  - stage: build
    script: "./build.sh"
  - stage: test
    script: "./tests.sh"
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: Y/5kW5eQ4mOVRkT6l+85W4kqvTNUhaGJlAMisocaf1E+E05g+R4CRKMoyWaExntxzagMqJ57BkBHFojpK5qzORRWhkK5JGQFQl1TauzslPzY9QEJQahC7xKdpy+tz0y5n11Hj9DBWZlkGNA6SF844WBc3dWLKVpzUs8lLHgG9rAHi3HDTG1RiwgU0mYyY/vWS2s+3sluWRomw/WheBtS65s+xgzUyo1rv8excFG1hezwkfWjk8uxK2e7Qf5hk+YJU41XuXlFKsFho8/oZ1CvsXRHYkwHSKmw8ZHUyiIjHj9xFLLWE0lxk8+X8qQwsy38Yg5s+l0M86uIELKP8xjtWmDDAEFnjXOwGb2Plu7j4vgcQ/i+H9stjW5o5X1t5jUBReTFM5aiqsR0/6G2oNrD6pAUAIDBpQ9tM6nmYFaNBSiuNUJQeCN2SNjNhh7TRYnW+m+2BuEKXkzFgISZtuVuTLIh8k0yErDD5LlJJe16F1Qnc8PyVpXXU6xaqHWwBYNOlEIvVlgRkCej3O+FYHmM+YRwxBipvMpd/GDA5S5so4do7VcL56JvsC3G/PFUv4kZUKS5aV3l+Nn3k91pxdRC0FU2ZMMbNltlTK/uJmPevxjJT0fIINAnYqKJFTlqYaLaTost3oLwsyW1+9TtfyYMrBICneDz4PiOSx6LobE7Kx8=
