language: csharp
solution: dips_lab1.sln
mono: none
dotnet: 2.0.0
dist: trusty
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./tests.sh
script:
  - ./build.sh
  - dotnet test ./TestsDipsLab1/TestsDipsLab1.csproj
