language: csharp
solution: dips_lab1.sln
mono: none
dotnet: 2.0.0
dist: trusty
jobs:
  include:
    - stage: before_script
      - chmod a+x ./build.sh
      - chmod a+x ./tests.sh
    - stage: build
      script: ./build.sh
    - stage: test
      script: ./test.sh
